Update MariaDB to 10.2.6
[mariadb-102]
- Update to MariaDB 10.2.6 GA
- refresh patches
- remove obsolete patches

diff --git a/patches/mysql-patches/mariadb-10.2.4-logrotate.patch b/patches/mysql-patches/mariadb-10.2.4-logrotate.patch
--- a/patches/mysql-patches/mariadb-10.2.4-logrotate.patch
+++ b/patches/mysql-patches/mariadb-10.2.4-logrotate.patch
@@ -18,18 +18,18 @@ Index: support-files/mysql-log-rotate.sh
          # create 600 mysql mysql
          notifempty
  	daily
-@@ -31,6 +31,14 @@
- 	   @bindir@/mysqladmin ping &>/dev/null
+@@ -32,6 +32,14 @@
  	then
- 	   @bindir@/mysqladmin flush-logs
-+	   ret=$?
-+	   if test $ret -ne 0
-+	   then
-+	      echo "/etc/logrotate.d/mariadb failed, probably because" >&2
-+	      echo "the root acount is protected by password." >&2
-+	      echo "See comments in /etc/logrotate.d/mariadb on how to fix this" >&2
-+	      exit $ret
-+	   fi
+ 	   @bindir@/mysqladmin --local flush-error-log \
+               flush-engine-log flush-general-log flush-slow-log
++           ret=$?
++           if test $ret -ne 0
++           then
++              echo "/etc/logrotate.d/mariadb failed, probably because" >&2
++              echo "the root acount is protected by password." >&2
++              echo "See comments in /etc/logrotate.d/mariadb on how to fix this" >&2
++              exit $ret
++           fi
  	fi
      endscript
  }
